---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 树上的二狗.
--- DateTime: 2025/4/8 下午6:18
---

local function check(num)
    if num == 0 then return true end
    local n = num
    while n > 0 do
        local digit = n % 10
        if digit == 0 or digit == 2 or digit == 4 then
            return true
        end
        n = math.floor(n / 10)
    end
    return false
end

local function main()
    local n = tonumber(io.read())

    local si = {}
    local ti = {}
    for i = 1, n do
        si[i] = tonumber(io.read())
    end
    for i = 1, n do
        ti[i] = tonumber(io.read())
    end

    local inp = 1
    local count = 0
    for i = 1, n do
        local temp
        if inp % 2 == 1 then
            temp = si[i]
        else
            temp = ti[i]
        end

        if check(temp) then
            count = count + 1
            inp = inp + 1
        end
    end
    print(count)
end

main()