---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 树上的二狗.
--- DateTime: 2025/3/13 下午5:40
---
local N = 10005
local n, ans = 0, 0
local a = {}
for i = 0, N do
    a[i] = {}
    for j = 0, N do
        a[i][j] = 0
    end
end

-- 读取输入
n = io.read("*number")
for _ = 1, n do
    local x1 = io.read("*number")
    local y1 = io.read("*number")
    local x2 = io.read("*number")
    local y2 = io.read("*number")
    a[x1][y1] = a[x1][y1] + 1
    a[x1][y2] = a[x1][y2] - 1
    a[x2][y1] = a[x2][y1] - 1
    a[x2][y2] = a[x2][y2] + 1
end

-- 计算二维前缀和
for i = 0, 10000 do
    for j = 0, 10000 do
        if i > 0 and j > 0 then
            a[i][j] = a[i][j] + a[i - 1][j] + a[i][j - 1] - a[i - 1][j - 1]
        elseif i > 0 then
            a[i][j] = a[i][j] + a[i - 1][j]
        elseif j > 0 then
            a[i][j] = a[i][j] + a[i][j - 1]
        end
        if a[i][j] ~= 0 then
            ans = ans + 1
        end
    end
end

-- 输出结果
print(ans)